// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfzYYc7fNs7Qdy_kMZDBcFFuUnHke8hOg',
    appId: '1:5232096751:web:30122111465e149a1bb21a',
    messagingSenderId: '5232096751',
    projectId: 'friendsphere-90f90',
    authDomain: 'friendsphere-90f90.firebaseapp.com',
    storageBucket: 'friendsphere-90f90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-U1sjFd_4b4g_xMW5YQq4Dt80E5fOCY',
    appId: '1:5232096751:android:b7223d06094fb4d51bb21a',
    messagingSenderId: '5232096751',
    projectId: 'friendsphere-90f90',
    storageBucket: 'friendsphere-90f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRWrhRXDyW2yUpylqm7MBXso5MnFUcAg',
    appId: '1:5232096751:ios:fa1827c3a1383a421bb21a',
    messagingSenderId: '5232096751',
    projectId: 'friendsphere-90f90',
    storageBucket: 'friendsphere-90f90.appspot.com',
    iosBundleId: 'com.example.sdpProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfzYYc7fNs7Qdy_kMZDBcFFuUnHke8hOg',
    appId: '1:5232096751:web:d66f61371d0aee461bb21a',
    messagingSenderId: '5232096751',
    projectId: 'friendsphere-90f90',
    authDomain: 'friendsphere-90f90.firebaseapp.com',
    storageBucket: 'friendsphere-90f90.appspot.com',
  );
}
